### ISSUE TITLE
The Swift server crashed 5 times in the last 3 minutes. The server will not be restarted

### ISSUE THREAD

**Issue by gperdomor** [jinmingjian/sde#13]
Using macOS Sierra
```
/Users/gustavoperdomo/.vscode/extensions/jinmingjian.sde-1.0.20170112/out/src/server/server.js:157
        throw err; //FIXME more friendly prompt
        ^

Error: spawn /usr/bin/sourcekitd-repl ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Info  - 3:40:48 PM] Connection to server got closed. Server will restart.
/Users/gustavoperdomo/.vscode/extensions/jinmingjian.sde-1.0.20170112/out/src/server/server.js:157
        throw err; //FIXME more friendly prompt
        ^

Error: spawn /usr/bin/sourcekitd-repl ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Info  - 3:40:49 PM] Connection to server got closed. Server will restart.
/Users/gustavoperdomo/.vscode/extensions/jinmingjian.sde-1.0.20170112/out/src/server/server.js:157
        throw err; //FIXME more friendly prompt
        ^

Error: spawn /usr/bin/sourcekitd-repl ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Info  - 3:40:49 PM] Connection to server got closed. Server will restart.
/Users/gustavoperdomo/.vscode/extensions/jinmingjian.sde-1.0.20170112/out/src/server/server.js:157
        throw err; //FIXME more friendly prompt
        ^

Error: spawn /usr/bin/sourcekitd-repl ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Info  - 3:40:49 PM] Connection to server got closed. Server will restart.
/Users/gustavoperdomo/.vscode/extensions/jinmingjian.sde-1.0.20170112/out/src/server/server.js:157
        throw err; //FIXME more friendly prompt
        ^

Error: spawn /usr/bin/sourcekitd-repl ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Error - 3:40:49 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by joscdk** [comment]
I get the same error:
Ubuntu 16.04
Swift 3.0.2

Anyone have link to a guide to install/compile sourcekitd-repl?

**Comment by mna** [comment]
You don't have the sourcekitd-repl tool in this location (`/usr/bin/sourcekitd-repl ENOENT`).

**Comment by vknabel** [comment]
@PuerkitoBio do you know where it is located on macOS?

**Comment by mna** [comment]
I'm trying to figure this out atm, looks like it isn't built by default (it's a test tool or something). I checked `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin` and it's not there.

**Comment by jinmingjian** [comment]
online just now. really thanks for all report. The choose of 'sourcekitd-repl' is not accident. It is a tool made by official Swift team. So it should work in all platform which Swift supports. It is great. 

The tool is also not built by default. I use a build preset file way (customized @ ~/.swift-build-presets) in my Linux which modified from [the official preset file](https://github.com/apple/swift/blob/master/utils/build-presets.ini).

**Comment by jinmingjian** [comment]
please wait a moment. I will share you a build preset in Linux which give you some hints.

**Comment by jinmingjian** [comment]
this preset file now lives [here](https://github.com/jinmingjian/swift-linux-build).

the "secret“ may be this:
--------------
...
extra-cmake-options="-DSWIFT_BUILD_SOURCEKIT:BOOL=ON -DSWIFT_TOOL_SOURCEKITD_REPL_BUILD=1"

dash-dash
 
swift-install-components=autolink-driver;compiler;clang-builtin-headers;stdlib;sdk-overlay;license;sourcekit-inproc;tools
...

at OSX, you may change: 
> sourcekit-inproc -> sourcekit-xpc-service

and component "tools" should corresponds to sourcekit side gen. 

extra-cmake-options is must for Linux. but I guess no harm for OSX.

And it needs two passes in Linux: First, disable "sourcekit-inproc" comopnent for libdispatch, and second enable "sourcekit-inproc" for itself.

@alblue recently introduce a PR to solve this problem, but seemly reverted...

**Comment by jinmingjian** [comment]
Add if some successfully, it may be possible to only ship the binary for macOS in that the sourcekit lib should already have existed which used by xcode.  Great.

**Comment by jinmingjian** [comment]
I just pushed new version into VSCode Marketplace which fixs #14 for macOS

**Comment by fwgreen** [comment]
I'm having the same problem on Ubuntu 16.04.  I'm using https://github.com/norio-nomura/docker-sourcekit-builder provides sourcekitd-repl.

**Comment by jinmingjian** [comment]
and note: we need SPM 3.1 for the info of project which is not available for 3.0. 

In macOS, it has fancy tool [swiftenv](https://github.com/kylef/swiftenv) for use.

More notes:
It can be hard coded by assumption with Sources or src by ablue. But this is too special. One workaround is to use build.yaml. However, this is a internal generated build file. It is better to based on "swfit package"(which is official interface to reflect Pacakge.swift itself)

**Comment by jinmingjian** [comment]
@fwgreen do you have sourcekitd-repl in path? How about you execute the following cmd in shell:
> which sourcekitd-repl

>sourcekitd-repl

**Comment by jinmingjian** [comment]
@fwgreen thanks for report for Linux. 

More note:
sourcekitd-repl  even can not be executed in my Arch default. Because the linked library name is not correct. The following workaround this:

> sudo ln -s /usr/lib/sourcekitdInProc.framework/sourcekitdInProc /usr/lib/sourcekitdInProc

But the ubuntu release is officially supported, so I guess the problem should not be there...

**Comment by jinmingjian** [comment]
@fwgreen  could you like to try some binary from my own build? :smile:

**Comment by fwgreen** [comment]
@jinmingjian I'll have to try and build it myself:  I tried running `sourcekitd-repl` and got an error.  Maybe the a complete language server written in TypeScript would save us 😄.  I'll try to build it and report back.

**Comment by fwgreen** [comment]
@jinmingjian I managed to get `sourcekitd-repl` working, but the error persists 😞

**Comment by jinmingjian** [comment]
@fwgreen if sourcekitd-repl works, then it almost becomes working for all. 

what is your exact error output?

and still show you output of the following cmd in shell:

> which sourcekitd-repl

**Comment by jinmingjian** [comment]
you add a sym link to /usr/bin/sourcekitd-repl. or use override configurations. You can see all configurable constants in Extensions's page in vscode:

![configs](https://cloud.githubusercontent.com/assets/237573/21918842/66c56f80-d990-11e6-9fe4-8f4c17e6ded7.png)

**Comment by jinmingjian** [comment]
ok, more detail config like this:

![sk_repl_path](https://cloud.githubusercontent.com/assets/237573/21919087/985f9a50-d992-11e6-9cd2-0653df12520c.png)

**Comment by rolandleth** [comment]
@PuerkitoBio I know this is not the place to ask, but I didn't manage to find the required info anywhere :( Any idea how to build the sourcekitd-repl / sourcekit on a mac?

**Comment by fwgreen** [comment]
`which sourcekitd-repl` returns
```
/usr/bin/sourcekitd-repl
```
`sourcekitd-repl` returns
```
Welcome to SourceKit.  Type ':help' for assistance.
(SourceKit) 
```
The output from vscode is
```
/home/fwgreen/.vscode/extensions/jinmingjian.sde-1.0.20170113/out/src/server/server.js:64
        throw err; //FIXME more friendly prompt
        ^

Error: spawn /usr/bin/sh ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Info  - 6:20:37 AM] Connection to server got closed. Server will restart.
/home/fwgreen/.vscode/extensions/jinmingjian.sde-1.0.20170113/out/src/server/server.js:64
        throw err; //FIXME more friendly prompt
        ^

Error: spawn /usr/bin/sh ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Info  - 6:20:38 AM] Connection to server got closed. Server will restart.
/home/fwgreen/.vscode/extensions/jinmingjian.sde-1.0.20170113/out/src/server/server.js:64
        throw err; //FIXME more friendly prompt
        ^

Error: spawn /usr/bin/sh ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Info  - 6:20:38 AM] Connection to server got closed. Server will restart.
/home/fwgreen/.vscode/extensions/jinmingjian.sde-1.0.20170113/out/src/server/server.js:64
        throw err; //FIXME more friendly prompt
        ^

Error: spawn /usr/bin/sh ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Info  - 6:20:38 AM] Connection to server got closed. Server will restart.
/home/fwgreen/.vscode/extensions/jinmingjian.sde-1.0.20170113/out/src/server/server.js:64
        throw err; //FIXME more friendly prompt
        ^

Error: spawn /usr/bin/sh ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Error - 6:20:39 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by vknabel** [comment]
@jinmingjian Thanks I got it to work on macOS  🎉

@rolandleth I needed to compile it manually.

```bash
$ mkdir swift-sources && cd swift-sources
# Probably other swift versions will work too
$ git clone --branch swift-DEVELOPMENT-SNAPSHOT-2017-01-05-a --depth 1 https://github.com/apple/swift
$ brew install cmake ninja
$ swift/utils/update-checkout --clone
# This will end with an error about master not found or so, just ignore it

# Now I edited `swift/utils/build-presets.init` according to @jinmingjian
# As follows https://gist.github.com/vknabel/170caee6b5883624f55c4d7f1b0b259c/revisions
# On the line starting with: 'swift-install-components='
# I replaced 'sourcekit-xpc-service' with 'sourcekit-inproc'
$ swift/utils/build-script # This takes a while

# sourcekitd-repl is now at
# build/Ninja-DebugAssert/swift-macosx-x86_64/bin/sourcekitd-repl
```

Now you can either link it to `/usr/bin` or set `"swift.path.sourcekitd_repl"` in Code to the appropriate path.

**Comment by jinmingjian** [comment]
@vknabel Cool!

**Comment by rolandleth** [comment]
@vknabel Awesome, thanks a lot! 🎉

**Comment by vknabel** [comment]
@fwgreen You are using the docker container, right? Did you execute `which sourcekitd_repl` in `docker run bash` or so? 
I guess the problem is that only your docker has `sourcekitd_repl`, whereas the rest of your computer (including VS Code) doesn't. Maybe you need to create a bash script that passes all Inputs to `docker run sourcekitd_repl` and link that file to `/usr/bin/sourcekitd_repl` outside docker.

**Comment by jinmingjian** [comment]
@fwgreen you met issue #14 in Linux... you have not **sh** in **/usr/bin/sh**, find your sh, do a sym link to **/usr/bin/sh**. I will add config option later for you.

> which sh

**Comment by jinmingjian** [comment]
@vknabel thanks for contributing ideas!

@rolandleth If you still have not build sourcekitd-repl successfully, you may wait for serveral days. I am considering add a simpler solution in #9. The implementation itself is trivial. But I hope to leave a space for further extension. So just wait several days. 

After #9 fixed, I plan to ship the binary in the package. For Linux, we still need sourcekitd library to build:(  For macOS, the state may be better, I guess sourcekitd have existed in that xcode, but we need to test. You can also help in this if interesting:)

**Comment by rolandleth** [comment]
@jinmingjian Oooh, that's great news! I already started building it, but I'll probably just delete everything after you release an update. Thanks!

**Comment by gperdomor** [comment]
Should be nice having `sourcekitd-repl` as a homebrew formula :D

**Comment by fwgreen** [comment]
@jinmingjian The symlink from `/bin/sh` to `/usr/bin/sh` did the trick!  Thanks.

**Comment by jinmingjian** [comment]
@fwgreen  #15 done. And I have published a new version. You can delete the sym link /usr/bin/sh now!

**Comment by jinmingjian** [comment]
@gperdomor very good formula for walking in the Swift edge

**Comment by gperdomor** [comment]
how can I build `sourcekitd-repl` in macOS?

**Comment by jinmingjian** [comment]
@gperdomor  great weekend build plan :sunglasses:  

do you test with above comments, especially by @vknabel in [this comment](https://github.com/jinmingjian/sde/issues/13#issuecomment-272424949)

**Comment by gperdomor** [comment]
yes, and after generating almost 20GB of files, and adding this line `"swift.path.sourcekitd_repl": "~/swift-sources/build/Ninja-DebugAssert/swift-macosx-x86_64/bin/sourcekitd-repl"`
 to `settings.json`in vscode,  the extension still failing

**Comment by jinmingjian** [comment]
@gperdomor what's your output of running sourcekitd-repl ? like this:

>  ~/swift-sources/build/Ninja-DebugAssert/swift-macosx-x86_64/bin/sourcekitd-repl

**Comment by jinmingjian** [comment]
@gperdomor and can you **use a full canonical path** like: /home/ABC/swift-sources/build/Ninja-DebugAssert/swift-macosx-x86_64/bin/sourcekitd-repl other than ~/... 

Because the ~ for the user's home is a shell shortcut which can not be understood by application.

NOTE: replace /home/ABC with your true user's home directory.

**Comment by bolismauro** [comment]
@gperdomor @vknabel Isn't it possibile for you to share the `sourcekitd-repl` you have built?
It should save a lot of time for other people that are trying to use sde for mac os

(I've no idea how big the file is to be honest)

@jinmingjian I'm super interested in using this extension instead of Xcode but I'm not knowledgeable in this things. I'll try to compile sourcekitd_repl from sources, but if #9 is fixed everything will work out of the box right? 

EDIT: this library wraps sourcekit in swift APIs, I guess they use something related, right?
https://github.com/jpsim/SourceKitten

**Comment by vknabel** [comment]
@bolismauro I uploaded the macOS binary for `sourcekitd-repl` for `swift-DEVELOPMENT-SNAPSHOT-2017-01-05-a`, but it worked fine in my own directory using another swift version. But I am not sure which version has actually been used.

[sourcekitd-repl.zip](https://github.com/jinmingjian/sde/files/706587/sourcekitd-repl.zip)

**Comment by gperdomor** [comment]
@jinmingjian I don't know why, but still fails with absolute path, but with the file provided by @vknabel works. Mine was compiled with swift-DEVELOPMENT-SNAPSHOT-2017-01-14-a.

Now I get this in the Output console of VSCode:
```
[Error - 10:29:23 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: This socket has been ended by the other party
  Code: -32603 
```

I run `./sourcekitd-repl --version`and get 
```
dyld: Library not loaded: @rpath/sourcekitd.framework/Versions/A/sourcekitd
  Referenced from: /Users/gustavoperdomo/./sourcekitd-repl
  Reason: image not found
Abort trap: 6
```

so sharing the file not working

**Comment by gperdomor** [comment]
@vknabel can you provide the updated preset file to see the updated lines?, maybe I'm doing something wrong in that step

**Comment by jinmingjian** [comment]
@bolismauro ideally yes :smile:  The effort in #9 will relax some requirements. But, as you know, I have not mac hardware equipped now. So, it may need some help to ensure #9's outcome to work for macOS. It seems the interests from macOS are larger than that of Linux in this issues! I am planning to give a macOS env to test for #9.

#9's outcome will be sourcekitd-repl like solution. It will be fully controlled by the SDE project and try to solve the tool building as you expect. The SDE does not use SourceKitten as I mentioned in #9. The sourcekitd-repl + nodejs-based language server will provide some equivalence to SourceKitten, or more. 

@vknabel  really thanks! It also helps for my testing. :+1:

**Comment by jinmingjian** [comment]
@gperdomor  the output just shows the socket close in that the background repl process do not run i think.  "dyld: Library not loaded" still show the "sourcekitd" library problem, but not sure how to fix... I am trying to get a macOS as soon as I can.

**Comment by vknabel** [comment]
@bolismauro Here are my changes to the `build-presets.ini` https://gist.github.com/vknabel/170caee6b5883624f55c4d7f1b0b259c/revisions.

I guess you need some `.dylib`s, not just the `sourcekitd-repl`, but they are all about 200 MB big and I don't know how many you need. I will test a bit later this day or tomorrow.

**Comment by bolismauro** [comment]
@vknabel I can also try to built it myself with you presets (I can't right now because of issues with the network, but I'll give it a try). Thanks for the help!

@jinmingjian amazing. I think that if you manage to have something working (and easily accessible) a lot of macos developers will give it a try. XCode (at least in my opinion) is not that great

**Comment by vknabel** [comment]
@bolismauro @gperdomor could you both get a working version?

@jinmingjian Do you know when sourcekitd-repl will be included by default in Swift? Could we "misuse" Travis to build us sourcekitd-repl for several Swift versions?

OT: If one uses the same version for the sourcekitd-repl and swift, the compile time is just awesome and feels much faster than in Xcode. With a watcher that runs swift test on changes, it would be even better (and faster!) than using livereload in JS.

**Comment by jinmingjian** [comment]
@vknabel sourcekitd-repl is just a tool for swift team's testing. So I do not expect it will be included in the download in any form. I think, it is not feasible to ask Swift team to support this tool public. And there is a bug I found. Given the tool is trivial in its implementation, this is also the reason behind what I propose #9. 

You mentioned Travis's ("misuse") usage is very promising :laughing: (Not sure if there are some limits) It is also useful for #9.

**Comment by jinmingjian** [comment]
@vknabel and cool response! vscode is also a charming tool! It is highly hackable in many aspects. You can do many things in the whole ecosystem. As you said, it is easy to add a watcher or runner even if the current sde project has not provided any test side support.

**Comment by gperdomor** [comment]
@vknabel @jinmingjian @bolismauro sadly no :(

**Comment by gperdomor** [comment]
I'm in Sierra 10.12.2 with the last version of Xcode FYI

**Comment by jinmingjian** [comment]
@gperdomor I just prepared a macOS env yesterday. I will try a look if I can do a help in this today.

**Comment by gperdomor** [comment]
@jinmingjian @vknabel the build finish, and the binary works in terminal, but the VSCode extension throws the same error, that's weird

**Comment by vknabel** [comment]
@gperdomor @bolismauro Do you use swiftest? You could run `swiftenv install DEVELOPMENT-SNAPSHOT-2017-01-05-a` and copy the `sourcekitd-repl` into `~/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2017-01-05-a/bin` (not sure if thats the right path, though).

MAYBE it works then. (the sourcekitd-repl needs to have the dylibs in `../lib` relative to itself)
Then either set the absolute path (expand the `~`) in your VS Code settings or if you want it linked to `/usr/bin`, you need to cd into `/usr/bin` and run `ln -s ../../Users/YOUR_USERNAME/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2017-01-05-a/bin/sourcekitd-repl` and then set the path in the settings to `/usr/bin/sourcekitd-repl`.

Hope it works.

**Comment by gperdomor** [comment]
@vknabel no, I'm using the swift from xcode, let me do that

**Comment by jinmingjian** [comment]
@gperdomor  Let all in toolchain matched is better as suggested by @vknabel via swiftenv.

If it still does not work, there is another config named "sde.enableTracing.LPServer" as I [mentioned above](https://github.com/jinmingjian/sde/issues/13#issuecomment-272361788). You enable it and post all output in "Swift" console windows here.

**Comment by vknabel** [comment]
@jinmingjian theoretically putting it into the toolchain would be better, but I compiled that Dev version. I am not sure whether both sourcekitd.frameworks are compatible

**Comment by gperdomor** [comment]
@vknabel 
```
installer: Package name is Swift Open Source Xcode Toolchain
installer: Installing at base path /
installer: The install was successful.
DEVELOPMENT-SNAPSHOT-2017-01-05-a has been installed.
```

but `~/.swiftenv/versions/` is empty

**Comment by TofPlay** [comment]
@jinmingjian In the installation process of SDE it would be possible to add the following tasks?
- Check Swift version
- Install the right Swift version automatically if it's not installed
- Check if sourcekitd-repl is install
- Install automatically sourcekitd-repl if it's not installed

**Comment by bolismauro** [comment]
@vknabel I had to work on other things, I'll read everything and try asap

**Comment by jinmingjian** [comment]
@gperdomor sorry for a little late. I have worked out a solution for the binary from @vknabel yesterday. You can use install_name_tool to help macOS to find the lib.

And I am planning __to release a experimental binary shipped version for macOS (and linux if possible) today__ before #9 fixed. :smile:

**Comment by jinmingjian** [comment]
@TofPlay thanks for suggestions. More friendly prompt is always pursued. But commonly "automatically" is not a way programmers like. A nicer pop-up message is more welcome than error output in console. I will look a suitable time window to do this :smile:

**Comment by jinmingjian** [comment]
@gperdomor new extension has been pushed. Can you have a try?

Make you install the latest development snapshot at "/Library/Developer/Toolchains/swift-latest.xctoolchain" (the default location for official snapshot. you can install it via swiftenv).

check version like this:
> $ /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin/swift -version
Apple Swift version 3.0-dev (LLVM 7e421db87c, Clang 8df9d5d9f9, Swift 6f08335ce0)
Target: x86_64-apple-macosx10.9

**Comment by jinmingjian** [comment]
sorry, the default behavior has not changed.  You should set the "swift.sourcekit.use_built_in_bin" config option to "true" to enable the experimental built-in sourcekit interface. 
Now this is only available for macOS. For Linux, we wait for when the default snapshot package includes the sourcekitd framework or I find some workaround for this.

**Comment by jinmingjian** [comment]
it is also much appreciated if some other macOS users can give me a feedback about this experimental feature.

**Comment by bolismauro** [comment]
I've installed the latest version.
Added this to my config
`"swift.sourcekit.use_built_in_bin": true`

I tried with your demo and I receive

```
[Error - 8:48:34 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: This socket has been ended by the other party
  Code: -32603 
```

The syntax highlight seems to be broken too.

I am missing something? It if is a problem, what extra info do you need?

**Comment by jinmingjian** [comment]
@bolismauro how about your the result of this command:
> /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin/swift -version

**Comment by jinmingjian** [comment]
and restart the vscode after setting the config

**Comment by bolismauro** [comment]
yes I have restarted it

Bug I guess the problem is this
```
~|⇒ /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin/swift -version
zsh: no such file or directory: /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin/swift
```

**Comment by jinmingjian** [comment]
that is the problem. do we install the latest development snapshot? in fact we depend on the latest 3.1 of swift.

**Comment by bolismauro** [comment]
Sorry for the silly question, how do I do it?

**Comment by jinmingjian** [comment]
@bolismauro [swiftenv](https://swiftenv.fuller.li/en/latest/) is easy to install and switch between different version. but you can also install it from the [official site](https://swift.org/download/#snapshots)

**Comment by bolismauro** [comment]
I'll try asap thanks 

I guess I have to install the latest snapshot, right?

**Comment by jinmingjian** [comment]
and I find the 2017-01-16 snapshot installed from swiftenv has problem when running swift repl and lldb with snapshot.  But I am not sure this is problem for the snapshot or the swiftenv. You can switch back easily by swiftenv.  I will continue to investigate this problem.

**Comment by jinmingjian** [comment]
@bolismauro welcome:)

**Comment by bolismauro** [comment]
```
~|⇒ swiftenv global
DEVELOPMENT-SNAPSHOT-2017-01-17-a
~|⇒ /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin/swift -version
Apple Swift version 3.0-dev (LLVM 7e421db87c, Clang 8df9d5d9f9, Swift 4db0ac6022)
Target: x86_64-apple-macosx10.9
```

It seems to work :)

I'll continue to test it in the following days :) Amazing.. I really hope that VS will replace Xcode sooner or later :D

**Comment by vknabel** [comment]
@bolismauro for me it worked, too. Thanks @jinmingjian! 🎉

Edit: I used installed DEVELOPMENT-SNAPSHOT-2017-01-17-a via swiftenv

**Comment by jinmingjian** [comment]
thanks for all, great news! it lays down the solid foundation for next iteration :beer:

**Comment by gperdomor** [comment]
Sorry for the delay... for me it worked, too
![giphy-2](https://cloud.githubusercontent.com/assets/371939/22067755/62365b70-dd71-11e6-9564-d468ec3b9147.gif)

**Comment by jinmingjian** [comment]
I have pushed release 2.0 into marketplace. There is no new feature in this release. But I overhaul the implementation. 

The biggest thing is that we do not need sourcekitd-repl any more. Instead, we need to build a new simple tool called [sourcekite](https://github.com/jinmingjian/sourcekite).  

Let me know if you problem. thanks for all :smiley:
